services:
  - type: web
    name: gestiondestock
    env: php
    buildCommand: composer install
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: APP_URL
        value: https://gestiondestock-z434.onrender.com

  - type: pserv
    name: gestiondestock-db
    env: postgresql
    plan: free
